version: "3.6"

services:

  rtl433:
    restart: always
    image: hertzg/rtl_433:latest
    container_name: ${PROJECT_NAME}-rtl433
    command: "-F http"
    devices:
      - /dev/bus/usb/001/003:/dev/bus/usb/001/003
    ports:
      - "8433:8433"
    volumes:
      - ./rtl_433/rtl_433.conf:/etc/rtl_433/rtl_433.conf

