version: "3.6"

services:

  raspiscan_server:
    build:
      context: .
      dockerfile: server/Dockerfile
    image: ${PROJECT_NAME}_server
    working_dir: /raspiscan/server
    command: '--experimental-modules --experimental-json-modules index.js'
    user: root
    container_name: ${PROJECT_NAME}_server
    restart: always
    volumes:
      - .:/raspiscan
      - /raspiscan/server/node_modules
      - /raspiscan/shared/node_modules
      - ./rtl_433/rtl_433.conf:/etc/rtl_433/rtl_433.conf
      - ./rtl_433/rtl-sdr.rules:/etc/udev/rules.d/rtl-sdr.rules
    ports:
      - "3000:3000"
    extra_hosts:
      - "host:${HOST_IP}"
      - "servant:192.168.178.34"
    environment:
      - DEBUG=true
      - VERBOSE=2
      - ENVIRONMENT=default
      - NODE_ENV=development
      - PWD=/raspiscan/server
      - SERVER_FRONTEND_PATH=config/frontend
      - HOST_IP=${HOST_IP}
    devices:
      - "${USB_DEVICE_SOURCE}:${USB_DEVICE_TARGET}"
    privileged: true

