version: "3.6"

networks:

  raspiscan:
    external: false
    name: ${PROJECT_NAME}

services:

  raspiscan_server:
    image: ghcr.io/seekwhencer/node-rtl433-ui:${DOCKER_IMAGE_VERSION}
    working_dir: /${PROJECT_NAME}/server
    command: '--experimental-modules --experimental-json-modules index.js'
    user: root
    container_name: ${PROJECT_NAME}_server
    restart: always
    volumes:
      - .env:/raspiscan/.env
      - ./server/config:/raspiscan/server/config

    #  or only the config file
    #  - ./server/config/default.conf:/raspiscan/server/config/default.conf
    networks:
      - raspiscan
    ports:
      - "${SERVER_PORT}:${SERVER_PORT_OUTSIDE}"
    extra_hosts:
      - "${MQTT_HOST}:${MQTT_HOST_IP}"
    environment:
      - DEBUG=true
      - VERBOSE=2
      # equals the config file: server/config/{ENVIRONMENT}.conf
      - ENVIRONMENT=default
      - NODE_ENV=production
      - PWD=/raspiscan/server
      # important, don't change it. the frontend production bundle is placed there
      - SERVER_FRONTEND_PATH=frontend
      # log topic and device events
      - SERVER_LOG_TOPICS=false
    devices:
      - "${USB_DEVICE_SOURCE}:${USB_DEVICE_TARGET}"
    privileged: true

