version: "3.6"

networks:

  raspiscan:
    external: false
    name: ${PROJECT_NAME}

services:

  raspiscan_server:
    build:
      context: .
      dockerfile: server/Dockerfile
    image: ${PROJECT_NAME}_server
    working_dir: /raspiscan/server

    # the app is not starting !
    # just enter:
    #
    #   docker exec -it raspiscan_server /bin/sh -c "node --experimental-modules --experimental-json-modules index.js"
    #
    # to run the server

    command: 'tail -f /dev/null'

    user: root
    container_name: ${PROJECT_NAME}_server
    restart: always
    volumes:
      - .:/raspiscan
      - ./rtl_433/rtl_433.conf:/etc/rtl_433/rtl_433.conf
      - ./rtl_433/rtl-sdr.rules:/etc/udev/rules.d/rtl-sdr.rules
    networks:
      - raspiscan
    ports:
      - "${SERVER_PORT}:${SERVER_PORT_OUTSIDE}"
    extra_hosts:
      - "${MQTT_HOST}:${MQTT_HOST_IP}"
    environment:
      - DEBUG=true
      - VERBOSE=2
      - ENVIRONMENT=default
      - NODE_ENV=development
      - PWD=/raspiscan/server
      # important change for development
      - SERVER_FRONTEND_PATH=../frontend/dist/dev
    devices:
      - "${USB_DEVICE_SOURCE}:${USB_DEVICE_TARGET}"
    privileged: true

